### ISSUE TITLE
Voice? 

### ISSUE THREAD

**Issue by xdrahmahx** [Xari0x/minimalist-hud#1]
Ability to see voice range and if voice is active or not?

**Comment by jordantoulain** [comment]
I'll add it as soon as possible!

**Comment by Xari0x** [comment]
Added on last version ! [[FREE] [SCRIPT] Minimalist HUD (Standalone)](https://forum.cfx.re/t/free-script-minimalist-hud-standalone/5238732/9)

**Comment by jordantoulain** [comment]
Added on last version ! [[FREE] [SCRIPT] Minimalist HUD (Standalone)](https://forum.cfx.re/t/free-script-minimalist-hud-standalone/5238732/9)

**Comment by xdrahmahx** [comment]
Last request  :P Stress ?

**Comment by jordantoulain** [comment]
> Last request :P Stress ?

Let's say it's a very specific request, few servers have a stress system, if you really need it you can either add it yourself (the script is not complicated to understand if you have experience) or I can do it for you without worries, however it won't be release.

**Comment by xdrahmahx** [comment]
if you could please. and thank you I'd appreciate it
